### ISSUE TITLE
can i download the required image resource

### ISSUE THREAD

**Issue by niu2x** [ewancoder/btp#2]

**Comment by ewancoder** [comment]
Wow, never thought that anyone will look into this :) Did not advertise this anywhere. So, this project is really, I mean really raw, only basic engine is working. I am trying to create a game in different programming languages from time to time, but eventually it stops and then I switch to another language. And because of limitations of pygame3 (high CPU usage, audio delays when using pulseaudio) I am planning on rewriting this again on pure C++ or maybe using Godot engine (preferable way). But here you go if you want to test it: https://mega.co.nz/#F!w0thmRwZ!UHbsUsbXMZhdDdfSitc9wA

**Comment by ewancoder** [comment]
Also note that you'll need to switch to "dev" branch (development), for "master" branch is nearly empty.

**Comment by ewancoder** [comment]
I guess now that I added link to media files into README.md, this issue can be closed.
